services:
  web:
      image: nginx:latest
      container_name: nginx
      restart: always
      build:
        context: .
        dockerfile: DockerfileNginx
      ports:
      - 80:80
      volumes:
      - ./daypayremittance.local:/usr/share/nginx/html/
      - ./default.conf:/etc/nginx/conf.d/default.conf
      links:
      - php
  sqlsrv:
      image: mcr.microsoft.com/mssql/server:2022-latest
      container_name: mssql
      build: 
        context: .
        dockerfile: DockerfileSql
      ports:
      - 1433:1433  
      volumes:
      - ./data:/var/opt/mssql/data
      networks:
      - network      
  php:
    image: php:8.1.0-fpm
    container_name: php8.1.0-fpm
    volumes:
      - ./daypayremittance.local:/usr/share/nginx/html/   
    build:
      context: .
      dockerfile: DockerfilePhp
networks:
  network:
    driver: bridge      